/* =====================================================================
   REFS.JS — standard references cited by every drug entry.
   Key -> {n: short label, f: full citation}
   ===================================================================== */
if (typeof REFS === 'undefined') { var REFS = {}; }
REFS = {
  /* ---------- resuscitation ---------- */
  'AHA2025':            {n:'AHA 2025 ACLS', f:'2025 American Heart Association Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care — Part 9: Adult Advanced Life Support. Circulation 2025;152(16):e245–e282. (Epinephrine 1 mg q3–5 min; amiodarone 300 mg then 150 mg; lidocaine 1–1.5 mg/kg then 0.5–0.75 mg/kg.)'},
  'AHA2025-PALS':       {n:'AHA 2025 PALS', f:'2025 AHA Guidelines for CPR and ECC — Part 10: Paediatric Basic and Advanced Life Support. Circulation 2025;152(16):e283–e320.'},
  'AHA2025-OPIOID':     {n:'AHA 2025 opioid', f:'2025 AHA Guidelines for CPR and ECC — Opioid-associated emergency response and naloxone administration.'},
  'AHA2025-ANAPHYLAXIS':{n:'AHA 2025 anaphylaxis', f:'2025 AHA Guidelines for CPR and ECC — Part 6: Anaphylaxis, adrenaline dosing and refractory anaphylaxis.'},
  'AHA2025-HTN':        {n:'AHA 2025 hypertension', f:'2025 AHA/ACC Guidelines for the Management of Adults with Hypertensive Emergencies.'},
  'AHA2025-ACS':        {n:'AHA 2025 ACS', f:'2025 AHA/ACC Guidelines for the Management of Acute Coronary Syndromes; 2025 AHA ACLS Part 9 tachyarrhythmia tables.'},
  'AHA2025-STROKE':     {n:'AHA 2025 stroke', f:'2025 AHA/ASA Guidelines for the Early Management of Patients with Acute Ischaemic Stroke (tenecteplase 0.25 mg/kg non-inferiority; alteplase 0.9 mg/kg max 90 mg).'},
  'AHA2025-SAH':        {n:'AHA 2025 SAH', f:'2023/2025 AHA/ASA Guideline for the Management of Patients with Aneurysmal Subarachnoid Haemorrhage (nimodipine 60 mg q4h × 21 days).'},
  'AHA2025-PE':         {n:'AHA 2025 PE', f:'2025 AHA Scientific Statement on Massive Pulmonary Embolism and Systemic Thrombolysis.'},
  'AHA-STROKE-2019':    {n:'AHA/ASA 2019 stroke', f:'Powers WJ et al. Guidelines for the Early Management of Patients With Acute Ischaemic Stroke: 2019 Update. Stroke 2019;50:e344–e418.'},
  'AHA2025-TOX':        {n:'AHA 2025 special resuscitation', f:'2025 AHA Guidelines — Part 11: Special Circumstances of Resuscitation (toxicology, drowning, pregnancy).'},
  'ERC2025':            {n:'ERC 2025 ALS', f:'European Resuscitation Council Guidelines 2025: Adult Advanced Life Support. Resuscitation 2025.'},
  'ERC2025-NEO':        {n:'ERC 2025 neonatal', f:'European Resuscitation Council Guidelines 2025: Newborn Life Support.'},
  'ERC2025-HYPERK':     {n:'ERC 2025 hyperkalaemia', f:'ERC/ESICM guidance on the emergency management of severe hyperkalaemia (calcium → insulin–dextrose → salbutamol → removal).'},
  'RESCUS-ANAPH':       {n:'Resus Council anaphylaxis', f:'Resuscitation Council UK. Anaphylaxis: Emergency Treatment for Adults and Children — 2021/2024 update (adrenaline IM 1:1000, weight bands, repeat every 5 min).'},
  'ISCCM-ALS':          {n:'ISCCM ALS', f:'Indian Society of Critical Care Medicine. Advanced Life Support / ACLS provider course materials and drug charts (current edition).'},

  /* ---------- paediatric life support ---------- */
  'APLS':               {n:'APLS 7th ed.', f:'Advanced Paediatric Life Support: The Practical Approach, 7th edition. Advanced Life Support Group / Wiley-Blackwell (weight formulas: <1 y (0.5 × months) + 4; 1–5 y (2 × age) + 8; 6–12 y (3 × age) + 7).'},
  'NRP2025':            {n:'NRP 8th/9th ed.', f:'Neonatal Resuscitation Program Textbook, 8th–9th edition. AAP/AHA (adrenaline 0.01–0.03 mg/kg IV/IO, 0.05–0.1 mg/kg ETT; volume 10 mL/kg).'},
  'IAP-NRP':            {n:'IAP NRP', f:'Indian Academy of Pediatrics — National Neonatology Forum. Neonatal Resuscitation Program guidelines (India).'},
  'IAP-EM':             {n:'IAP emergency', f:'Indian Academy of Pediatrics. Textbook of Paediatric Emergency Medicine / IAP standard protocols for paediatric emergencies.'},
  'IAP-SE':             {n:'IAP status epilepticus', f:'Indian Academy of Pediatrics / ILAE India consensus on the management of status epilepticus in children.'},
  'LUSCOMBE':           {n:'Luscombe & Owens', f:'Luscombe MD, Owens BM. Weight estimation in resuscitation: is the current formula still valid? Arch Dis Child 2009;94:412–413. (Weight = 3 × age + 7, valid 1–15 years; more accurate than APLS in modern, heavier children.)'},
  'WHO-CHILD-GROWTH':   {n:'WHO growth standards', f:'WHO Child Growth Standards and Reference 2007 (5–19 years) — median weight-for-age by sex, used for the WHO-based weight estimate in this tool.'},
  'NELSON':             {n:'Nelson 22nd ed.', f:'Kliegman RM, St Geme JW III, Blum NJ, Shah SS, Tasker RC, Wilson KM, Schuh AM, Mack CL (eds). Nelson Textbook of Pediatrics, 22nd edition, 2 volumes. Elsevier; 2024. ISBN 978-0-323-88305-4. — Part VII Emergency Medicine, Critical Care and Anesthesia; Part VI Fluid and Electrolyte Disorders; Part XXI The Nervous System.'},
  /* ---------- paediatric dose references and textbooks ----------
     These six are the paediatric dosing backbone of this tool. Harriet Lane
     (ch. 30 Drug Dosages), Singh & Deorari and the Gupta formulary are
     dose-per-kg references; Nelson, Ghai and the PG Textbook supply the
     disease and critical-care context.                              */
  'HARRIET-LANE':       {n:'Harriet Lane 23rd ed.', f:'The Johns Hopkins Hospital. Anderson CC, Kapoor S, Mark TE (eds). The Harriet Lane Handbook: A Manual for Pediatric House Officers, 23rd edition. Elsevier; 2023. ISBN 978-0-323-87698-8. — Ch.1 Emergency and Critical Care Management; Ch.3 Toxicology; Ch.6 Analgesia and Procedural Sedation; Ch.11 Fluids and Electrolytes; Ch.18 Neonatology; Ch.30 Drug Dosages (Paediatric Drug Formulary, updated by Carlton K.K. Lee, PharmD, MPH); Ch.31 Drugs in Kidney Failure.'},
  'FENTON-2013':        {n:'Fenton preterm growth chart 2013',
                         f:'Fenton TR, Kim JH. A systematic review and meta-analysis to revise the Fenton growth chart for preterm infants. BMC Pediatrics 2013;13:39. Birth-weight 50th centile by postmenstrual age (anchors 24/28/30/32/34/36/40 weeks, linearly interpolated between); the WHO Child Growth Standard takes over at term.'},
  'SINGH-DOSES':        {n:'Singh — Drug Dosages in Children 11th ed.', f:'Singh M (Meharban Singh), Deorari AK. Drug Dosages in Children, 11th edition. CBS Publishers & Distributors Pvt Ltd; New Delhi; 2024. ISBN 978-93-5466-877-7. — daily dosage per unit body weight, frequency and route for every drug listed alphabetically; cautions, contraindications and adverse effects; drugs to avoid in G6PD deficiency and in breastfeeding; standard adult doses alongside; Indian trade names with product strengths.'},
  'GUPTA-FORMULARY':    {n:'Gupta — Pediatric Drug Formulary', f:'Gupta P (Piyush Gupta), Bedi N. Pediatric Drug Formulary. Jaypee Brothers Medical Publishers; New Delhi; 2023. — Indian paediatric doses, concentrations, dilutions, compatibility and adverse-effect profiles.'},
  'PG-TB-PED':          {n:'PG Textbook of Pediatrics 3rd ed.', f:'Gupta P, Menon PSN, Ramji S, Lodha R (eds). PG (Postgraduate) Textbook of Pediatrics, 3rd edition, Vols 1–3. Jaypee Brothers Medical Publishers; New Delhi; 2022 (reprint 2024, ISBN 978-93-5465-121-2). — Vol 1 General Pediatrics, Intensive Care and Neonatology; Vol 3 Annexure B: Pediatric Drug Formulary (Bedi N, Dewan P) and Annexure A: Laboratory Reference Values.'},
  'IAP-STG':            {n:'IAP Standard Treatment Guidelines', f:'Kumar R, Ratageri V, Gupta P (eds). IAP Standard Treatment Guidelines. Jaypee Brothers Medical Publishers; New Delhi; 2023. — Indian Academy of Pediatrics consensus treatment protocols for common paediatric conditions, including drug, dose, route and duration.'},
  'GHAI10':             {n:'Ghai Essential Pediatrics 10th ed.', f:'Paul VK, Bagga A (eds). Ghai Essential Pediatrics, 10th edition. CBS Publishers & Distributors Pvt Ltd; New Delhi; 2023. ISBN 978-93-5466-507-3. — IMNCI management algorithms, poisonings, fluid and electrolyte disorders, critical care and the National Immunization Schedule.'},
  'BNFC':               {n:'BNF for Children', f:'BNF for Children (BNFC), current edition — BMJ Group/Pharmaceutical Press/RPS (paediatric dosing and formulations).'},

  /* ---------- general drug references ---------- */
  'BNF':                {n:'BNF', f:'British National Formulary (BNF), current edition — BMJ Group/Pharmaceutical Press/RPS.'},
  'SANFORD':            {n:'Sanford Guide', f:'The Sanford Guide to Antimicrobial Therapy, current edition. Antimicrobial Therapy Inc.'},
  'MARINO':             {n:'Marino\'s ICU Book', f:'Marino PL. The ICU Book, 4th edition. Wolters Kluwer (and The Little ICU Book).'},
  'TINTINALLI':         {n:'Tintinalli', f:'Tintinalli JE et al. Tintinalli\'s Emergency Medicine: A Comprehensive Study Guide, 9th/10th edition. McGraw-Hill.'},
  'GOLDFRANK':          {n:'Goldfrank\'s', f:'Nelson LS et al. Goldfrank\'s Toxicologic Emergencies, 11th/12th edition. McGraw-Hill.'},
  'MORGAN':             {n:'Morgan & Mikhail', f:'Morgan GE, Mikhail MS. Clinical Anesthesiology, 6th/7th edition (induction agents, NMBAs, reversal).'},
  'WHO-PALLIATIVE':     {n:'WHO analgesic ladder', f:'WHO. Cancer pain relief and palliative care — the analgesic ladder; WHO model list of essential medicines, 23rd list (2023).'},
  'WHO-ANALGESIC':      {n:'WHO essential medicines', f:'WHO Model List of Essential Medicines, 23rd list (2023) — adult and paediatric core lists.'},
  'IP-COMPENDIUM':      {n:'Indian Pharmacopoeia', f:'Indian Pharmacopoeia 2018 (and Addenda to 2024) — Indian Pharmacopoeia Commission, Ghaziabad; NFDC/IP formulation standards.'},
  'ISCCM-ABX':          {n:'ISCCM antimicrobial', f:'Indian Society of Critical Care Medicine. Guidelines on the rational use of antimicrobials in the ICU; ISCCM position statements on sepsis and multidrug-resistant organisms.'},
  'ISCCM-AMR':          {n:'ISCCM AMR', f:'ISCCM/NITI Aayog/ICMR guidance on antimicrobial resistance, carbapenem-resistant Gram-negative infection and colistin/polymyxin dosing in India.'},
  'CONSENSUS-COLISTIN': {n:'Colistin consensus', f:'Tsuji BT et al. First International Consensus Guidelines for the Optimal Use of the Polymyxins. Pharmacotherapy 2019;39:64–97 (loading dose 9 MIU ≈ 300 mg CBA, then maintenance based on CrCl).'},
  'ASHP-VANCO':         {n:'ASHP vancomycin', f:'Rybak MJ et al. Therapeutic Monitoring of Vancomycin: A Revised Consensus Guideline (AUC/MIC 400–600 target). Am J Health-Syst Pharm 2020;77:835–864.'},
  'BSAC-ABX':           {n:'BSAC', f:'British Society for Antimicrobial Chemotherapy — dosage and extended-infusion guidance for β-lactams.'},

  /* ---------- sepsis / shock ---------- */
  'SSC2021':            {n:'Surviving Sepsis 2021', f:'Evans L et al. Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock 2021. Intensive Care Med 2021;47:1181–1247.'},
  'SSC2021-PEDS':       {n:'Surviving Sepsis Paeds 2020', f:'Weiss SL et al. Surviving Sepsis Campaign International Guidelines for the Management of Septic Shock and Sepsis-Associated Organ Dysfunction in Children. Pediatr Crit Care Med 2020;21:e82–e106.'},
  'ISCCM-SEP':          {n:'ISCCM sepsis', f:'Indian Society of Critical Care Medicine. Guidelines for the Management of Sepsis and Septic Shock in India (current edition); ISCCM sepsis bundle and vasopressor charts.'},
  'SMART-TRIAL':        {n:'SMART/SPLIT/BaSICS', f:'Semler MW et al. Balanced Crystalloid versus Saline in Critically Ill Adults (SMART). NEJM 2018;378:829–839; Finfer S et al. (SPLIT) JAMA 2015; Zampieri FG et al. (BaSICS) JAMA 2021.'},
  'SOAP-II':            {n:'SOAP II', f:'De Backer D et al. Comparison of Dopamine and Norepinephrine in the Treatment of Shock. NEJM 2010;362:779–789.'},
  'ISCCM-CARDIO':       {n:'ISCCM cardiovascular', f:'ISCCM/CSI consensus statements on shock, acute heart failure and vasoactive therapy in Indian ICUs.'},

  /* ---------- cardiovascular ---------- */
  'ESC-PE':             {n:'ESC PE 2019', f:'Konstantinides SV et al. 2019 ESC Guidelines for the Diagnosis and Management of Acute Pulmonary Embolism.'},
  'ESC-ACS':            {n:'ESC ACS', f:'ESC Guidelines for the Management of Acute Coronary Syndromes (current edition).'},
  'ESC-STEMI':          {n:'ESC STEMI', f:'Ibanez B et al. ESC Guidelines for the Management of Acute Myocardial Infarction in Patients Presenting with ST-Segment Elevation.'},
  'ESC-HTN':            {n:'ESC hypertension', f:'ESC/ESH Guidelines for the Management of Arterial Hypertension (current edition) — hypertensive emergency section.'},
  'ESC-HF':             {n:'ESC heart failure', f:'McDonagh TA et al. ESC Guidelines for the Diagnosis and Treatment of Acute and Chronic Heart Failure.'},
  'ESC-PH':             {n:'ESC pulmonary HTN', f:'ESC/ERS Guidelines for the Diagnosis and Treatment of Pulmonary Hypertension (current edition).'},
  'CSI-STEMI':          {n:'CSI India STEMI', f:'Cardiological Society of India. Consensus statement on the management of STEMI in India (pharmaco-invasive strategy, tenecteplase/streptokinase dosing).'},
  'TRACE2':             {n:'TRACE-2', f:'Wang Y et al. Tenecteplase versus Alteplase for Acute Ischaemic Stroke (TRACE-2): a multicentre, open-label, randomised non-inferiority trial. Lancet 2023;401:701–711.'},
  'ACCP-VTE':           {n:'ACCP antithrombotic', f:'American College of Chest Physicians Evidence-Based Clinical Practice Guidelines: Antithrombotic Therapy for VTE Disease (current edition).'},
  'ACCP-PEDS':          {n:'ACCP paediatric VTE', f:'Monagle P et al. Antithrombotic Therapy in Neonates and Children: ACCP Evidence-Based Clinical Practice Guidelines.'},
  'ASH-PEDS-VTE':       {n:'ASH paediatric VTE', f:'American Society of Hematology 2018 Guidelines for the Management of Venous Thromboembolism (paediatric).'},
  'BSH-WARFARIN':       {n:'BSH warfarin', f:'British Society for Haematology. Guidelines on oral anticoagulation with warfarin; Keeling D et al. Br J Haematol 2011.'},
  'BSH-TRANSFUSION':    {n:'BSH transfusion', f:'British Society for Haematology Guidelines on the Use of Blood Components (FFP, cryoprecipitate, platelets); MoHFW India National Guidelines on Blood Transfusion (2024).'},
  'ISCCM-TRAUMA':       {n:'ISCCM trauma', f:'ISCCM/Indian trauma care guidelines on major haemorrhage and massive transfusion protocols.'},
  'CRASH2':             {n:'CRASH-2', f:'CRASH-2 Collaborators. Effects of tranexamic acid on death, vascular occlusive events and blood transfusion in trauma patients with significant haemorrhage. Lancet 2010;375:2195–2204.'},
  'WOMAN-TRIAL':        {n:'WOMAN trial', f:'WOMAN Trial Collaborators. Effect of early tranexamic acid administration on mortality in post-partum haemorrhage. Lancet 2017;389:2105–2116.'},
  'ISCCM-HF':           {n:'ISCCM heart failure', f:'ISCCM/CSI consensus on the management of acute heart failure and cardiogenic shock in India.'},

  /* ---------- sedation / neuro ---------- */
  'ISCCM-SEDATION':     {n:'ISCCM sedation', f:'Indian Society of Critical Care Medicine. Guidelines on Analgesia, Sedation and Delirium in the ICU (India-adapted PADIS).'},
  'PADIS2018':          {n:'PADIS 2018', f:'Devlin JW et al. Clinical Practice Guidelines for the Prevention and Management of Pain, Agitation/Sedation, Delirium, Immobility and Sleep Disruption in Adult ICU Patients. Crit Care Med 2018;46:e825–e873.'},
  'ISCCM-DELIRIUM':     {n:'ISCCM delirium', f:'ISCCM position statement on ICU delirium assessment (CAM-ICU / ICDSC) and management in India.'},
  'ISCCM-INTUBATION':   {n:'ISCCM intubation', f:'ISCCM/DAS India consensus on emergency tracheal intubation and the critically ill airway.'},
  'DAS-AIRWAY':         {n:'DAS airway', f:'Difficult Airway Society (UK) / ASA guidelines for management of the difficult airway and failed intubation.'},
  'NCS-STATUS':         {n:'Neurocritical Care SE', f:'Brophy GM et al. Guidelines for the Evaluation and Management of Status Epilepticus. Neurocrit Care 2012;17:3–23 (and the 2023 update).'},
  'AES2016':            {n:'AES 2016 SE', f:'Glauser T et al. Evidence-Based Guideline: Treatment of Convulsive Status Epilepticus in Children and Adults — Report of the American Epilepsy Society Guideline Subcommittee. Epilepsy Curr 2016;16:48–61.'},
  'ESICM-SE':           {n:'ESICM status epilepticus', f:'Kondziella D et al. European consensus-based statement on the management of status epilepticus. Intensive Care Med 2023;49:527–555.'},
  'ESETT':              {n:'ESETT', f:'Kapur J et al. Randomized Trial of Three Anticonvulsant Medications for Status Epilepticus (ESETT). NEJM 2019;381:2103–2113.'},
  'BTF-TBI':            {n:'Brain Trauma Foundation', f:'Carney N et al. Guidelines for the Management of Severe Traumatic Brain Injury, 4th edition. Brain Trauma Foundation 2016/2017.'},
  'NCS-ICP':            {n:'Neurocritical Care ICP', f:'Neurocritical Care Society / AHA-ASA guidelines on the management of elevated intracranial pressure and cerebral oedema.'},
  'NCS-SAH':            {n:'Neurocritical Care SAH', f:'Neurocritical Care Society Multidisciplinary Consensus Conference Guidelines for the Management of Aneurysmal Subarachnoid Hemorrhage.'},
  'ICTUS':              {n:'ICTUS citicoline', f:'Dávalos A et al. Citicoline in the treatment of acute ischaemic stroke (ICTUS): an international, randomised, multicentre trial. Lancet 2012;380:349–357.'},
  'CRASH':              {n:'CRASH corticosteroids', f:'CRASH Collaborators. Final results of the CRASH trial (corticosteroids in head injury). Lancet 2005;365:1957–1959 — increased mortality with corticosteroids in TBI.'},
  'MHAUS':              {n:'MHAUS', f:'Malignant Hyperthermia Association of the United States. Emergency Therapeutic Guidelines for MH (dantrolene 2.5 mg/kg IV, repeat to ≈10 mg/kg).'},
  'AAGBI-MH':           {n:'AAGBI MH', f:'Association of Anaesthetists of Great Britain and Ireland. Malignant Hyperthermia: Guidance for Management (current edition).'},
  'ASRA-LAST':          {n:'ASRA LAST', f:'Neal JM et al. The Third ASRA Practice Advisory on Local Anesthetic Systemic Toxicity. Reg Anesth Pain Med 2020;45:166–182.'},
  'AAGBI-LAST':         {n:'AAGBI LAST', f:'AAGBI Safety Guideline: Management of Severe Local Anaesthetic Toxicity (current edition).'},

  /* ---------- respiratory ---------- */
  'GINA2024':           {n:'GINA', f:'Global Initiative for Asthma (GINA). Global Strategy for Asthma Management and Prevention, current edition.'},
  'GOLD2025':           {n:'GOLD', f:'Global Initiative for Chronic Obstructive Lung Disease (GOLD). Global Strategy for the Diagnosis, Management and Prevention of COPD, current edition.'},
  'BTS-ASTHMA':         {n:'BTS/SIGN asthma', f:'British Thoracic Society / SIGN. British Guideline on the Management of Asthma (current edition).'},
  'BTS-CROUP':          {n:'BTS croup', f:'BTS / national croup guidance; NICE Clinical Knowledge Summaries — Croup (dexamethasone 0.15–0.6 mg/kg; nebulised adrenaline 0.5 mL/kg max 5 mL).'},
  'IAP-ASTHMA':         {n:'IAP asthma', f:'Indian Academy of Pediatrics. Revised guidelines for the diagnosis and management of asthma in Indian children (current edition).'},
  'IAP-PPHN':           {n:'IAP PPHN', f:'Indian Academy of Pediatrics / NNF consensus on persistent pulmonary hypertension of the newborn.'},
  'ESICM-ARDS':         {n:'ESICM ARDS', f:'ESICM/ATS/SCCM ARDS definition and management guidance; lung-protective ventilation and prone positioning protocols.'},
  'ACURASYS':           {n:'ACURASYS', f:'Papazian L et al. Neuromuscular Blockers in Early Acute Respiratory Distress Syndrome (ACURASYS). NEJM 2010;363:1107–1116 (cisatracurium 37.5 mg/h × 48 h).'},
  'ROSE-ARDS':          {n:'ROSE', f:'Moss M et al. Early Neuromuscular Blockade in the Acute Respiratory Distress Syndrome (ROSE). NEJM 2019;380:1997–2008 (no benefit with routine early NMBAs).'},
  'DEXA-ARDS':          {n:'DEXA-ARDS', f:'Villar J et al. Dexamethasone treatment for the acute respiratory distress syndrome (DEXA-ARDS). Lancet Respir Med 2020;8:267–276.'},
  'AAP-BRONCHIOLITIS':  {n:'AAP bronchiolitis', f:'Ralston SL et al. Clinical Practice Guideline: The Diagnosis, Management and Prevention of Bronchiolitis. Pediatrics 2014;134:e1474–e1502.'},
  'NICE-NG9':           {n:'NICE bronchiolitis', f:'NICE NG9. Bronchiolitis in children: diagnosis and management (current edition).'},
  'IAP-BRONCHIOLITIS':  {n:'IAP bronchiolitis', f:'Indian Academy of Pediatrics. Clinical practice guidelines for bronchiolitis in Indian children.'},
  'FDA-SILDENAFIL':     {n:'FDA sildenafil PAH', f:'FDA Drug Safety Communication — sildenafil (Revatio) for PAH in children: dose-related mortality signal at high doses.'},

  /* ---------- renal / fluids / electrolytes ---------- */
  'KDIGO-AKI':          {n:'KDIGO AKI', f:'KDIGO Clinical Practice Guideline for Acute Kidney Injury (2012) and the 2024 KDIGO AKI Guideline update; KDIGO guidance on CRRT anticoagulation.'},
  'KDIGO-CRRT':         {n:'KDIGO CRRT', f:'KDIGO AKI guideline — recommendation for regional citrate anticoagulation in CRRT where there is no contraindication.'},
  'ESICM-CRRT':         {n:'ESICM CRRT', f:'ESICM best-practice guidance on continuous renal replacement therapy: anticoagulation, dosing and monitoring.'},
  'ISCCM-CRRT':         {n:'ISCCM CRRT', f:'ISCCM position statement on CRRT practice and anticoagulation in Indian ICUs.'},
  'UKKA-HYPERK':        {n:'UKKA hyperkalaemia', f:'UK Kidney Association. Clinical Practice Guideline: The Emergency Management of Severe Hyperkalaemia (current edition).'},
  'UKKA-HYPOK':         {n:'UKKA hypokalaemia', f:'UK Kidney Association. Clinical Practice Guideline: The Management of Hypokalaemia.'},
  'UKKA-HYPOMAG':       {n:'UKKA hypomagnesaemia', f:'UK Kidney Association. Clinical Practice Guideline: Magnesium Disorders.'},
  'ESICM-HYPO':         {n:'ESICM hyponatraemia', f:'Spasovski G et al. Clinical Practice Guideline on Diagnosis and Treatment of Hyponatraemia (ESICM/ERA-EDTA/ESA). Eur J Endocrinol 2014;170:G1–G47.'},
  'US-HYPO-EXPERT':     {n:'US hyponatraemia panel', f:'Verbalis JG et al. Diagnosis, Evaluation and Treatment of Hyponatremia: Expert Panel Recommendations. Am J Med 2013;126:S1–S42.'},
  'ADROGUE':            {n:'Adrogué–Madias', f:'Adrogué HJ, Madias NE. Hyponatremia and Hypernatremia. NEJM 2000;342:1581–1589 (free-water deficit and correction-rate formulas).'},
  'BICAR-ICU':          {n:'BICAR-ICU', f:'Jaber S et al. Sodium Bicarbonate Therapy for Patients with Severe Metabolic Acidemia in the ICU (BICAR-ICU). Lancet 2018;392:31–40.'},
  'NICE-CG174':         {n:'NICE IV fluids', f:'NICE CG174. Intravenous Fluid Therapy in Adults and Children in Hospital (current edition).'},
  'IAP-FLUID':          {n:'IAP fluids', f:'Indian Academy of Pediatrics. Guidelines on intravenous fluid therapy in children.'},
  'AAP-HYPONAT':        {n:'AAP maintenance fluids', f:'AAP Committee on Drugs/Hospital Care. Maintenance Intravenous Fluids in Pediatric Patients Receiving Care in Inpatient, Acute-Care, and Emergency Settings. Pediatrics 2018;142:e20181489 — use isotonic fluids.'},
  'NICE-REFEEDING':     {n:'NICE refeeding', f:'NICE CG32. Nutrition Support for Adults: Oral Nutrition Support, Enteral Tube Feeding and Parenteral Nutrition.'},
  'ASPEN-REFEEDING':    {n:'ASPEN refeeding', f:'ASPEN Consensus Recommendations for Refeeding Syndrome. Nutr Clin Pract 2020;35:178–195.'},
  'NPSA-KCL':           {n:'NPSA potassium alert', f:'NHS/NPSA Patient Safety Alert 22: Safer Administration of Intravenous Potassium Chloride (never-event status for undiluted IV KCl).'},
  'ESICM-AB':           {n:'ESICM acid–base', f:'ESICM guidance on the management of metabolic acidosis and alkalosis in the critically ill.'},

  /* ---------- endocrine ---------- */
  'ADA-DKA':            {n:'ADA DKA/HHS', f:'American Diabetes Association. Hyperglycemic Crises in Adult Patients With Diabetes (DKA/HHS) — Standards of Care, current edition.'},
  'ADA-HYPO':           {n:'ADA hypoglycaemia', f:'ADA Standards of Medical Care in Diabetes — Glycemic Targets and Hypoglycemia sections, current edition.'},
  'ADA-INPATIENT':      {n:'ADA inpatient glucose', f:'ADA Standards of Care — Diabetes Care in the Hospital (target 140–180 mg/dL; insulin infusion protocols).'},
  'JBDS-DKA':           {n:'JBDS DKA', f:'Joint British Diabetes Societies for Inpatient Care. The Management of Diabetic Ketoacidosis in Adults — Updated Consensus Guideline (current edition).'},
  'ISPAD2022':          {n:'ISPAD DKA', f:'Diabetes Mellitus in Children and Adolescents — ISPAD Clinical Practice Consensus Guidelines: Diabetic Ketoacidosis and Hyperglycemic Hyperosmolar State (2022).'},
  'IAP-DKA':            {n:'IAP DKA', f:'Indian Society of Pediatric and Adolescent Diabetes (ISPAD-India) / IAP guidelines on diabetes and DKA in Indian children.'},
  'NICE-NG18':          {n:'NICE diabetes', f:'NICE NG18. Diabetes (type 1 and type 2) in under 19s: management; NICE NG28 type 2 diabetes in adults.'},
  'ATA-THYROTOXICOSIS':   {n:'ATA thyrotoxicosis', f:'American Thyroid Association Guidelines for the Diagnosis and Management of Hyperthyroidism and Other Causes of Thyrotoxicosis.'},
  'JTA-STORM':          {n:'Thyroid storm (Japan)', f:'Akamizu T et al. Diagnostic criteria, clinical features and incidence of thyroid storm based on nationwide surveys (Japanese Thyroid Association guidelines).'},
  'ATA-HYPOTHYROID':    {n:'ATA hypothyroidism', f:'American Thyroid Association Guidelines for the Diagnosis and Management of Hypothyroidism.'},
  'ETA-MYXOEDEMA':      {n:'ETA myxoedema coma', f:'European Thyroid Association Guideline on the Management of Myxoedema Coma.'},
  'ENDO-ADRENAL':       {n:'Endocrine Society adrenal', f:'Bornstein SR et al. Diagnosis and Treatment of Primary Adrenal Insufficiency: An Endocrine Society Clinical Practice Guideline.'},
  'ESPE-ADRENAL':       {n:'ESPE adrenal crisis', f:'Flück CE et al. Consensus Statement on the Diagnosis and Treatment of Adrenal Insufficiency (ESPE/LWPES).'},
  'SCCM-GLUCOSE':       {n:'SCCM glucose', f:'SCCM/AACE consensus on inpatient glycemic control; Jacobi J et al. Guidelines for the Use of an Insulin Infusion for the Management of Hyperglycemia in Critically Ill Patients.'},
  'NICE-SUGAR':         {n:'NICE-SUGAR', f:'NICE-SUGAR Study Investigators. Intensive versus Conventional Glucose Control in Critically Ill Patients. NEJM 2009;360:1283–1297.'},
  'ISCCM-ENDO':         {n:'ISCCM endocrine', f:'ISCCM position statements on endocrine emergencies in the ICU.'},
  'RCP-WE':             {n:'RCP Wernicke', f:'Royal College of Physicians. Thiamine to prevent Wernicke encephalopathy in emergency presentations (national patient safety guidance).'},
  'EFNS-WE':            {n:'EFNS Wernicke', f:'EFNS guidelines for diagnosis, therapy and prevention of Wernicke encephalopathy (Galvin R et al., Eur J Neurol 2010).'},
  'MHRA-PARA':          {n:'MHRA paracetamol', f:'MHRA / UK Commission on Human Medicines guidance on intravenous paracetamol dosing and hepatotoxicity risk in low body weight and malnutrition.'},
  'MHRA-VPA':           {n:'MHRA valproate', f:'MHRA Drug Safety Update — valproate: hepatic, pancreatic and hyperammonaemic toxicity; pregnancy prevention programme.'},
  'ESMO-HYPERCALCAEMIA':{n:'ESMO hypercalcaemia', f:'Coleman R et al. ESMO Clinical Practice Guidelines on bone health in cancer / hypercalcaemia of malignancy.'},
  'ESMO-BONE':          {n:'ESMO bone metastases', f:'ESMO Clinical Practice Guidelines — Bone metastases and malignant hypercalcaemia.'},
  'FDA-TOLVAPTAN':      {n:'FDA tolvaptan', f:'FDA Drug Safety Communication — tolvaptan and the risk of liver injury; boxed warning for ADPKD.'},
  'ENDO-DI':            {n:'Endocrine Society DI', f:'Endocrine Society / European guidance on the diagnosis and management of diabetes insipidus.'},

  /* ---------- GI / liver ---------- */
  'AASLD-VARICEAL':     {n:'AASLD varices', f:'Baveno VII / AASLD Guidance on Portal Hypertension and Bleeding in Cirrhosis (terlipressin/octreotide + ceftriaxone + restrictive transfusion + endoscopy ≤12 h).'},
  'EASL-LIVER':         {n:'EASL liver', f:'EASL Clinical Practice Guidelines on the management of patients with decompensated cirrhosis.'},
  'ISCCM-LIVER':        {n:'ISCCM liver', f:'ISCCM guidance on the management of acute-on-chronic liver failure and variceal bleeding in Indian ICUs.'},
  'BSG-VARICEAL':       {n:'BSG variceal bleed', f:'British Society of Gastroenterology guidance on the management of acute variceal bleeding.'},
  'AASLD-HE':           {n:'AASLD hepatic enceph', f:'Vilstrup H et al. Hepatic Encephalopathy in Chronic Liver Disease: AASLD/EASL Practice Guideline.'},
  'EASL-HE':            {n:'EASL hepatic enceph', f:'EASL Clinical Practice Guidelines — Hepatic Encephalopathy in Chronic Liver Disease.'},
  'AASLD-ALF':          {n:'AASLD acute liver failure', f:'Lee WM et al. AASLD Guidelines for the Management of Acute Liver Failure (N-acetylcysteine in non-paracetamol ALF).'},
  'EASL-ALF':           {n:'EASL acute liver failure', f:'EASL Clinical Practice Guidelines on the management of acute (fulminant) liver failure.'},
  'ACG-UGIB':           {n:'ACG upper GI bleed', f:'Laine L et al. ACG Clinical Guideline: Upper Gastrointestinal and Ulcer Bleeding.'},
  'ESGE-UGIB':          {n:'ESGE upper GI bleed', f:'ESGE Guideline: Diagnosis and Management of Nonvariceal Upper Gastrointestinal Hemorrhage.'},
  'ACG-OGILVIE':        {n:'ACG Ogilvie', f:'Ogilvie syndrome / acute colonic pseudo-obstruction guidance (neostigmine 2 mg IV with atropine at the bedside).'},
  'ASGE-OGILVIE':       {n:'ASGE Ogilvie', f:'ASGE guidance on the role of endoscopy in acute colonic pseudo-obstruction.'},
  'ISCCM-SUP':          {n:'ISCCM stress ulcer', f:'ISCCM/Indian guidance on stress ulcer prophylaxis in the ICU.'},
  'SUP-ICU':            {n:'SUP-ICU', f:'Krag M et al. Pantoprazole in the Intensive Care Unit (SUP-ICU). NEJM 2018;379:1991–2000.'},
  'PEPTIC':             {n:'PEPTIC', f:'Ye Z et al. Gastrointestinal Bleeding and Mortality in Critically Ill Adults Receiving Stress Ulcer Prophylaxis with PPI vs H2RA (PEPTIC). JAMA 2020;324:1412–1423.'},
  'SCCM-NUTRITION':     {n:'SCCM/ASPEN nutrition', f:'SCCM/ASPEN Clinical Practice Guidelines for the Provision of Nutrition Support Therapy in the Adult Critically Ill Patient.'},
  'ISCCM-NUTRITION':    {n:'ISCCM nutrition', f:'ISCCM guidelines on nutrition support in Indian ICUs.'},
  'ESGE-CORROSIVE':     {n:'ESGE corrosive', f:'ESGE guideline on the endoscopic management of caustic ingestion; Zargar classification.'},
  'WSES-CORROSIVE':     {n:'WSES corrosive', f:'WSES guidance on the management of caustic ingestion and corrosive injury.'},
  'IAP-COLIC':          {n:'IAP colic', f:'IAP/Indian guidance on the management of renal and biliary colic.'},
  'ASHP-CINV':          {n:'ASHP CINV', f:'ASCO/NCCN/ASHP guidance on the prevention of chemotherapy-induced nausea and vomiting.'},
  'FDA-METOCLOPRAMIDE': {n:'FDA metoclopramide', f:'FDA Boxed Warning — metoclopramide and tardive dyskinesia (do not exceed 12 weeks).'},
  'ISCCM-ANALGESIA':    {n:'ISCCM analgesia', f:'ISCCM guidance on multimodal analgesia in the ICU.'},

  /* ---------- infectious diseases ---------- */
  'IDSA-MRSA':          {n:'IDSA MRSA', f:'Liu C et al. IDSA Clinical Practice Guidelines for the Treatment of MRSA Infections in Adults and Children.'},
  'IDSA-CANDIDA':       {n:'IDSA candidiasis', f:'Pappas PG et al. IDSA Clinical Practice Guideline for the Management of Candidiasis.'},
  'IDSA-ASPERGILLOSIS': {n:'IDSA aspergillosis', f:'Patterson TF et al. IDSA Practice Guideline for the Diagnosis and Management of Aspergillosis.'},
  'IDSA-CRYPTO':        {n:'IDSA cryptococcosis', f:'Perfect JR et al. IDSA Clinical Practice Guidelines for the Management of Cryptococcal Disease.'},
  'IDSA-MENINGITIS':    {n:'IDSA meningitis', f:'Tunkel AR et al. IDSA Practice Guidelines for the Management of Bacterial Meningitis.'},
  'IDSA-ENCEPHALITIS':  {n:'IDSA encephalitis', f:'Tunkel AR et al. IDSA Guidelines for the Management of Encephalitis.'},
  'IDSA-PCP':           {n:'IDSA PCP', f:'Guidelines for the Prevention and Treatment of Opportunistic Infections — Pneumocystis jirovecii pneumonia.'},
  'IDSA-NSTI':          {n:'IDSA skin/soft tissue', f:'Stevens DL et al. IDSA Practice Guidelines for the Diagnosis and Management of Skin and Soft Tissue Infections.'},
  'IDSA-AMR':           {n:'IDSA AMR', f:'IDSA Guidance on the Treatment of Antimicrobial-Resistant Gram-Negative Infections (CRE, Pseudomonas, Acinetobacter).'},
  'IDSA-CDIFF':         {n:'IDSA C. difficile', f:'IDSA/SHEA Clinical Practice Guideline for Clostridioides difficile Infection in Adults and Children.'},
  'ESCMID-CRE':         {n:'ESCMID CRE', f:'ESCMID guidance on the treatment of carbapenem-resistant Enterobacterales.'},
  'ESCMID-MENINGITIS':  {n:'ESCMID meningitis', f:'ESCMID/EFNS Guideline on the Management of Community-Acquired Bacterial Meningitis.'},
  'ECMM-MUCOR':         {n:'ECMM mucormycosis', f:'Cornely OA et al. Global guideline for the diagnosis and management of mucormycosis (ECMM/MSG). Liposomal amphotericin B 5–10 mg/kg/day is first-line.'},
  'ISCCM-FUNGAL':       {n:'ISCCM fungal', f:'ISCCM guidance on invasive fungal infections in Indian ICUs, including post-COVID mucormycosis.'},
  'IAP-MENINGITIS':     {n:'IAP meningitis', f:'Indian Academy of Pediatrics / IAP standard treatment guidelines on bacterial meningitis in children.'},
  'IAP-CNS':            {n:'IAP CNS infections', f:'IAP guidance on CNS infections including HSV encephalitis in Indian children.'},
  'IDSA-INFLUENZA':     {n:'IDSA influenza', f:'Uyeki TM et al. IDSA Clinical Practice Guidelines for the Diagnosis and Treatment of Influenza.'},
  'IAP-INFLUENZA':      {n:'IAP influenza', f:'Indian Academy of Pediatrics guidelines on influenza prevention and management in children.'},
  'WHO-THERAPEUTICS':   {n:'WHO therapeutics', f:'WHO living guidance on therapeutics for COVID-19 / viral pneumonia (remdesivir).'},
  'ICMR-COVID':         {n:'ICMR', f:'ICMR National Task Force clinical management guidance (remdesivir, steroids, anticoagulation).'},
  'AST-CMV':            {n:'AST CMV', f:'American Society of Transplantation Infectious Diseases Community of Practice — CMV management.'},
  'NIH-OI':             {n:'NIH opportunistic infections', f:'NIH/CDC/HIVMA Guidelines for the Prevention and Treatment of Opportunistic Infections in Adults and Adolescents with HIV.'},
  'WHO-MALARIA':        {n:'WHO malaria', f:'WHO Guidelines for Malaria (current edition): IV artesunate is first-line for severe malaria in adults, children and pregnancy; delayed haemolysis surveillance.'},
  'NVBDCP-MALARIA':     {n:'NVBDCP malaria', f:'National Vector Borne Disease Control Programme / National Centre for Vector Borne Diseases Control. National Framework for Malaria Elimination and National Drug Policy for Malaria, India (current edition).'},
  'IAP-MALARIA':        {n:'IAP malaria', f:'Indian Academy of Pediatrics. Guidelines for the management of malaria in children.'},
  'NVBDCP-KALA':        {n:'NVBDCP kala-azar', f:'NVBDCP/NVBDC. National guidelines for kala-azar (visceral leishmaniasis) elimination programme in India — single-dose liposomal amphotericin B 10 mg/kg.'},
  'WHO-LEISH':          {n:'WHO leishmaniasis', f:'WHO Guidelines for the Treatment of Visceral Leishmaniasis.'},
  'WHO-TB':             {n:'WHO TB', f:'WHO Consolidated Guidelines on Tuberculosis: treatment, drug-resistant TB and TB preventive treatment (current edition).'},
  'NTEP-INDIA':         {n:'NTEP India', f:'National Tuberculosis Elimination Programme (NTEP), Ministry of Health & Family Welfare, Government of India. Technical and Operational Guidelines for TB Control in India (current edition) — weight-band FDC dosing and Nikshay registration.'},
  'IDSA-TB':            {n:'IDSA/ATS TB', f:'Nahid P et al. Official ATS/CDC/IDSA Clinical Practice Guidelines: Treatment of Drug-Susceptible Tuberculosis.'},
  'WHO-LEPTO':          {n:'WHO leptospirosis', f:'WHO/IAPCM guidance on the diagnosis and management of leptospirosis.'},
  'CDC-SYPHILIS':       {n:'CDC syphilis', f:'CDC Sexually Transmitted Infections Treatment Guidelines — Neurosyphilis (aqueous penicillin G 18–24 MIU/day × 10–14 days).'},
  'WHO-DIPHTHERIA':     {n:'WHO diphtheria', f:'WHO. Diphtheria vaccine and antitoxin position paper; WHO immunological basis for immunization.'},
  'IAP-DIPHTHERIA':     {n:'IAP diphtheria', f:'Indian Academy of Pediatrics. Guidelines on the management of diphtheria; NCDC diphtheria surveillance guidance.'},
  'NCDC-DIPHTHERIA':    {n:'NCDC diphtheria', f:'National Centre for Disease Control, India. Operational Guidelines for Diphtheria Case Management.'},
  'WHO-TETANUS':        {n:'WHO tetanus', f:'WHO. Tetanus vaccines: WHO position paper; WHO current recommendations for treatment of tetanus.'},
  'IAP-TETANUS':        {n:'IAP tetanus', f:'Indian Academy of Pediatrics. Guidelines on tetanus prophylaxis and the management of neonatal and other tetanus.'},
  'CDC-TETANUS':        {n:'CDC tetanus', f:'CDC Tetanus Wound Management and ACIP recommendations (HTIG 250 IU for prophylaxis; 3,000–6,000 IU for established tetanus).'},
  'WHO-NTD':            {n:'WHO NTD', f:'WHO guidelines on neglected tropical diseases — strongyloidiasis, onchocerciasis, lymphatic filariasis, soil-transmitted helminths.'},
  'CDC-STRONGYLOIDES':  {n:'CDC strongyloides', f:'CDC guidance on strongyloidiasis; ivermectin 200 mcg/kg/day and management of hyperinfection syndrome.'},
  'IAP-ABX':            {n:'IAP antibiotics', f:'Indian Academy of Pediatrics. Guidelines on the rational use of antibiotics in children (current edition).'},
  'IAP-SCRUB':          {n:'IAP scrub typhus', f:'Indian Academy of Pediatrics / ICMR consensus on scrub typhus and rickettsial infections in India (doxycycline first-line; azithromycin alternative).'},
  'ISCCM-RICKETTSIA':   {n:'ISCCM rickettsial', f:'ICMR/ISCCM guidelines for the management of rickettsial infections, scrub typhus and leptospirosis in India.'},
  'AHA-RHD':            {n:'AHA rheumatic fever', f:'Gewitz MH et al. Revision of the Jones Criteria and AHA guidance on acute rheumatic fever and rheumatic heart disease; secondary prophylaxis with benzathine penicillin G.'},
  'WHO-RHD':            {n:'WHO RHD', f:'WHO. Rheumatic fever and rheumatic heart disease: report of a WHO expert consultation; secondary prophylaxis recommendations.'},
  'IAP-RHD':            {n:'IAP RHD', f:'Indian Academy of Pediatrics consensus on the management of rheumatic fever and rheumatic heart disease in India.'},
  'NCD-RHD-INDIA':      {n:'India RHD programme', f:'Ministry of Health & Family Welfare, Government of India. National Programme for Prevention and Control of Rheumatic Heart Disease — benzathine penicillin G every 3–4 weeks.'},
  'AHA-KAWASAKI':       {n:'AHA Kawasaki', f:'McCrindle BW et al. Diagnosis, Treatment and Long-Term Management of Kawasaki Disease: AHA Scientific Statement. Circulation 2017;135:e927–e999.'},
  'IAP-KAWASAKI':       {n:'IAP Kawasaki', f:'Indian Academy of Pediatrics. Revised guidelines on Kawasaki disease in Indian children.'},
  'WHO-DIARRHOEA':      {n:'WHO diarrhoea', f:'WHO/UNICEF. The Treatment of Diarrhoea: A Manual for Physicians and Other Senior Health Workers (ORS Plans A/B/C; zinc 10–20 mg × 14 days).'},
  'IAP-DIARRHOEA':      {n:'IAP diarrhoea', f:'Indian Academy of Pediatrics. Guidelines on the management of acute diarrhoea in children.'},
  'UNICEF-ZINC':        {n:'UNICEF zinc', f:'UNICEF/WHO joint statement on clinical management of acute diarrhoea — zinc supplementation.'},
  'NVBDCP-IDCF':        {n:'IDCF India', f:'Integrated Diarrhoea Control Framework (IDCF), MoHFW India — ORS + zinc 14-day campaign.'},
  'WHO-MEASLES':        {n:'WHO measles', f:'WHO. Measles vaccines: WHO position paper; vitamin A for measles (age-banded 50,000/100,000/200,000 IU on days 1 and 2).'},
  'IAP-MEASLES':        {n:'IAP measles', f:'Indian Academy of Pediatrics. Guidelines on measles management and vitamin A supplementation.'},
  'WHO-SAM':            {n:'WHO SAM', f:'WHO. Guidelines on the management of severe acute malnutrition in infants and children (vitamin A, zinc, F-75/F-100, antibiotics).'},
  'NVBDCP-MEASLES':     {n:'NVBDCP measles', f:'NVBDC/IDCF measles elimination programme — vitamin A supplementation schedule.'},
  'IDSA-ESBL':          {n:'IDSA ESBL', f:'IDSA Guidance on the Treatment of Antimicrobial-Resistant Gram-Negative Infections — ESBL-E, AmpC and carbapenemase-producing organisms.'},
  'IDSA-AMP':           {n:'IDSA cefepime', f:'IDSA/ESCMID guidance on cefepime dosing, extended infusion and neurotoxicity.'},
  'FDA-QUINOLONE':      {n:'FDA fluoroquinolone', f:'FDA Drug Safety Communication — fluoroquinolone class warnings: tendinitis/tendon rupture, peripheral neuropathy, CNS effects, aortic aneurysm, dysglycaemia, mental health effects.'},
  'FDA-TIGE':           {n:'FDA tigecycline', f:'FDA Boxed Warning — tigecycline: increased all-cause mortality versus comparators.'},
  'ATS-AMINOGLYCOSIDE': {n:'ATS aminoglycoside', f:'ATS/IDSA guidance on aminoglycoside dosing, extended-interval dosing and therapeutic drug monitoring.'},

  /* ---------- toxicology / envenomation ---------- */
  'NATL-SNAKEBITE-2024':{n:'National Snakebite Protocol 2024', f:'Ministry of Health & Family Welfare / WHO India. National Clinical Protocol for the Management of Snakebite in India, 2024 (10 vials ASV initial; haemotoxic 6-hour rule, max 30 vials; neurotoxic 1–2-hour rule, max 20 vials; same dose in children; atropine–neostigmine test).'},
  'NHM-SNAKEBITE':      {n:'NHM snakebite', f:'National Health Mission, MoHFW India. Guidelines for the Management of Snakebite (STG series) — ASV dosage, reconstitution and administration schedule.'},
  'WHO-SNAKEBITE':      {n:'WHO snakebite', f:'WHO. Guidelines for the Management of Snakebites, 2nd edition (WHO Regional Office for South-East Asia).'},
  'ISCCM-ENVENOM':      {n:'ISCCM envenomation', f:'ISCCM consensus on the management of snakebite and scorpion envenomation in Indian ICUs.'},
  'BAWASKAR-PRAZOSIN':  {n:'Bawaskar prazosin', f:'Bawaskar HS, Bawaskar PH. Prazosin therapy and scorpion envenomation. J Assoc Physicians India 2000;48:1175–1180; and Efficacy and safety of scorpion antivenom plus prazosin (BMJ Open 2011) — prazosin 30 mcg/kg in children, 0.5 mg in adults, 3-hourly.'},
  'WHO-OP':             {n:'WHO pesticide poisoning', f:'WHO. Guidelines for the Management of Poisoning Due to Organophosphorus and Carbamate Pesticides; WHO Recommended Classification of Pesticides by Hazard.'},
  'AIIMS-OP':           {n:'AIIMS OP poisoning', f:'AIIMS New Delhi. Management protocol for organophosphorus poisoning (atropinisation endpoints, pralidoxime dosing, intermediate syndrome).'},
  'ICMR-PESTICIDE':     {n:'ICMR pesticide', f:'ICMR. Guidelines for the Management of Acute Pesticide Poisoning; National Poisons Information Centre (AIIMS) protocols.'},
  'IAP-TOX':            {n:'IAP toxicology', f:'Indian Academy of Pediatrics / IAP textbook chapters on paediatric poisoning and envenomation in India.'},
  'AIIMS-ALP':          {n:'AIIMS aluminium phosphide', f:'AIIMS/New Delhi and Indian literature on aluminium phosphide poisoning — magnesium sulfate regimens, decontamination and supportive care.'},
  'EXPERT-HIET':        {n:'HIET consensus', f:'Greene SL et al. Expert Consensus Recommendations: Improving Diagnosis, Management and Outcome From High-Dose Insulin Therapy in Poisoning. J Med Toxicol 2023;19:1–17.'},
  'EXPERT-CCB':         {n:'CCB overdose consensus', f:'Expert consensus on calcium-channel-blocker poisoning — calcium, high-dose insulin, lipid emulsion, ECMO.'},
  'EXPERT-METHANOL':    {n:'Toxic alcohol consensus', f:'Expert consensus / EAPCCT-AACT statements on methanol and ethylene glycol poisoning; WHO toxic-alcohol outbreak guidance.'},
  'WHO-TOXIC-ALCOHOL':  {n:'WHO toxic alcohols', f:'WHO guidance on the public-health management of methanol poisoning outbreaks (illicit liquor).'},
  'ICMR-HOOCH':         {n:'ICMR hooch', f:'ICMR / Indian public-health literature on illicit-liquor (hooch) methanol outbreak management.'},
  'EXPERT-METHB':       {n:'Methaemoglobinaemia', f:'Expert guidance on acquired methaemoglobinaemia — methylene blue 1–2 mg/kg; G6PD deficiency contraindication; serotonin-syndrome interaction.'},
  'EXPERT-ILE':         {n:'Lipid emulsion', f:'Expert consensus on intravenous lipid emulsion therapy for lipophilic drug overdose (as per ASRA/AAGBI LAST guidance).'},
  'EXPERT-CYANIDE':     {n:'Cyanide', f:'FDA Cyanokit labelling; expert guidance on cyanide poisoning and the nitrite–thiosulfate alternative kit.'},
  'FDA-CYANOKIT':       {n:'FDA Cyanokit', f:'FDA Cyanokit (hydroxocobalamin) prescribing information and post-marketing safety communications.'},
  'EXPERT-VALPROATE':   {n:'Valproate toxicity', f:'Expert guidance on valproate overdose — L-carnitine 100 mg/kg load then 15 mg/kg q4h; haemodialysis.'},
  'EXPERT-DIGOXIN':     {n:'Digoxin toxicity', f:'Expert guidance on digoxin and cardiac-glycoside plant (oleander/Thevetia) poisoning — Fab fragment dosing formulas.'},
  'EXPERT-SALICYLATE':  {n:'Salicylate', f:'Expert consensus on salicylate poisoning — urinary alkalinisation and haemodialysis criteria.'},
  'EXPERT-TCA':         {n:'TCA overdose', f:'Expert consensus on tricyclic antidepressant overdose — sodium bicarbonate, avoidance of physostigmine and class I/III antiarrhythmics.'},
  'EXPERT-ANTICHOLINERGIC':{n:'Anticholinergic', f:'Expert guidance on anticholinergic toxicity — benzodiazepines first-line; physostigmine only for secure diagnoses without TCA features.'},
  'EXPERT-SEROTONIN':   {n:'Serotonin syndrome', f:'Boyer EW, Shannon M. The Serotonin Syndrome. NEJM 2005;352:1112–1120; Hunter Serotonin Toxicity Criteria.'},
  'EXPERT-NMS':         {n:'NMS', f:'Neuroleptic malignant syndrome expert guidance (stop the antipsychotic, cooling, benzodiazepines, bromocriptine/dantrolene).'},
  'EXPERT-RODENTICIDE': {n:'Superwarfarin', f:'Expert guidance on long-acting anticoagulant rodenticide (brodifacoum) poisoning — high-dose prolonged vitamin K1.'},
  'ASAM-WD':            {n:'ASAM alcohol withdrawal', f:'American Society of Addiction Medicine. Clinical Practice Guideline on the Management of Alcohol Withdrawal Syndrome (2020).'},
  'RCPSY-AW':           {n:'RCPsych alcohol', f:'Royal College of Psychiatrists. Medical management of alcohol withdrawal (current guidance).'},
  'AACT-CHARCOAL':      {n:'Charcoal position', f:'AACT/EAPCCT Position Paper: Single-dose and Multiple-dose Activated Charcoal.'},
  'AACT-NAC':           {n:'NAC position', f:'AACT/EAPCCT/WHO position statements on N-acetylcysteine in paracetamol poisoning; modified 2-bag regimens.'},
  'UK-PARACETAMOL':     {n:'UK paracetamol', f:'MHRA/UK guidance on the management of paracetamol overdose — treat all patients above the 100 mg/L treatment line regardless of risk stratification.'},
  'EAPCCT':             {n:'EAPCCT', f:'European Association of Poisons Centres and Clinical Toxicologists position statements.'},
  'AHA-TOX':            {n:'AHA toxicology', f:'AHA/ERC guidance on resuscitation in special circumstances — toxicological cardiac arrest.'},

  /* ---------- obstetric / neonatal ---------- */
  'ACOG-ECLAMPSIA':     {n:'ACOG eclampsia', f:'ACOG Practice Bulletin — Gestational Hypertension and Preeclampsia; magnesium sulfate regimens (Zuspan and Pritchard).'},
  'WHO-ECLAMPSIA':      {n:'WHO pre-eclampsia', f:'WHO Recommendations for the Prevention and Treatment of Pre-eclampsia and Eclampsia (magnesium sulfate; antihypertensives for SBP ≥160 or DBP ≥110).'},
  'NICE-NG133':         {n:'NICE hypertensive pregnancy', f:'NICE NG133. Hypertension in pregnancy: diagnosis and management.'},
  'FOGSI':              {n:'FOGSI India', f:'Federation of Obstetric and Gynaecological Societies of India (FOGSI) clinical practice recommendations on pre-eclampsia, eclampsia and PPH.'},
  'MAGPIE':             {n:'Magpie trial', f:'Magpie Trial Collaborative Group. Do women with pre-eclampsia, and their babies, benefit from magnesium sulphate? Lancet 2002;359:1877–1890.'},
  'WHO-PPH':            {n:'WHO PPH', f:'WHO Recommendations for the Prevention and Treatment of Post-Partum Haemorrhage; WHO PPH care bundle (E-MOTIVE).'},
  'ACOG-PPH':           {n:'ACOG PPH', f:'ACOG Practice Bulletin — Postpartum Hemorrhage (uterotonic sequence, TXA, escalation to surgical/radiological management).'},
  'FOGSI-PPH':          {n:'FOGSI PPH', f:'FOGSI Clinical Practice Recommendations on the Management of Post-Partum Haemorrhage in India.'},
  'WHO-ACS':            {n:'WHO antenatal steroids', f:'WHO Recommendations on Antenatal Corticosteroids for Improving Preterm Birth Outcomes (2022).'},
  'ACOG-ACS':           {n:'ACOG antenatal steroids', f:'ACOG Committee Opinion — Antenatal Corticosteroid Therapy for Fetal Maturation.'},
  'ACOG-HTN-PREG':      {n:'ACOG hypertension in pregnancy', f:'ACOG Practice Bulletin on hypertensive disorders of pregnancy — acute-onset severe hypertension treatment algorithms (labetalol, hydralazine, nifedipine).'},
  'NICE-NG25':          {n:'NICE preterm labour', f:'NICE NG25. Preterm labour and birth.'},
  'ALPS':               {n:'ALPS trial', f:'Gyamfi-Bannerman C et al. Antenatal Betamethasone for Women at Risk for Late Preterm Delivery (ALPS). NEJM 2016;374:1311–1320.'},
  'WHO-PREECLAMPSIA':   {n:'WHO pre-eclampsia', f:'WHO Recommendations for the Prevention and Treatment of Pre-eclampsia and Eclampsia.'},
  'IAP-NEO-SEPSIS':     {n:'IAP neonatal sepsis', f:'Indian Academy of Pediatrics / National Neonatology Forum. Standard Treatment Guidelines for Neonatal Sepsis (ampicillin + gentamicin; cloxacillin + amikacin for late-onset).'},
  'WHO-NEO':            {n:'WHO neonatal', f:'WHO. Management of possible serious bacterial infection in young infants when referral is not feasible; WHO recommendations on newborn health.'},
  'NICE-NG195':         {n:'NICE neonatal infection', f:'NICE NG195. Neonatal infection: antibiotics for prevention and treatment.'},
  'IAP-NICU':           {n:'IAP/NNF NICU', f:'Indian Academy of Pediatrics / National Neonatology Forum. Guidelines on neonatal intensive care: apnoea, surfactant, PDA, hypoglycaemia, jaundice, seizures.'},
  'AAP-RDS':            {n:'AAP RDS', f:'AAP Policy Statement on antenatal steroids and surfactant for RDS; Polin RA. Surfactant administration.'},
  'EURO-RDS':           {n:'European RDS', f:'Sweet DG et al. European Consensus Guidelines on the Management of Respiratory Distress Syndrome (current edition) — surfactant dosing and LISA.'},
  'CAP-TRIAL':          {n:'CAP trial', f:'Schmidt B et al. Caffeine Therapy for Apnea of Prematurity (CAP). NEJM 2006;354:2112–2121.'},
  'AAP-NEO-GLUCOSE':    {n:'AAP neonatal glucose', f:'AAP Committee on Fetus and Newborn. Postnatal Glucose Homeostasis in Late-Preterm and Term Infants. Pediatrics 2011;127:575–579.'},
  'IAP-NEO-HYPO':       {n:'IAP neonatal hypoglycaemia', f:'IAP/NNF consensus on the management of neonatal hypoglycaemia (10% dextrose 2 mL/kg; GIR 6–8 mg/kg/min).'},
  'PES-NEO':            {n:'Paediatric endocrine neonatal', f:'Pediatric Endocrine Society recommendations for the management of persistent neonatal hypoglycaemia (glucagon, diazoxide, octreotide).'},
  'PEDIATRIC-CARDIOLOGY':{n:'Paediatric cardiology', f:'Moss & Adams\' Heart Disease in Infants, Children and Adolescents — prostaglandin E1 for duct-dependent lesions.'},
  'IAP-NEO-SEIZURE':    {n:'IAP neonatal seizures', f:'IAP/NNF and ILAE guidance on neonatal seizures — phenobarbitone 20 mg/kg first-line, add-on 10 mg/kg up to 40 mg/kg.'},
  'WHO-NEONATAL':       {n:'WHO neonatal seizures', f:'WHO guidance on the management of neonatal seizures.'},
  'IAP-ENDO':           {n:'IAP endocrine', f:'Indian Academy of Pediatrics. Textbook of Paediatric Endocrinology; IAP guidance on adrenal crisis and CAH.'},
  'IAP-FEVER':          {n:'IAP fever', f:'Indian Academy of Pediatrics. Clinical practice guidelines on the management of fever in children — paracetamol 10–15 mg/kg/dose.'},
  'IAP-GE':             {n:'IAP gastroenteritis', f:'Indian Academy of Pediatrics guidelines on acute gastroenteritis — ORS, zinc, no anti-motility drugs.'},
  'IAP-ANAPHYLAXIS':    {n:'IAP anaphylaxis', f:'Indian Academy of Pediatrics / IAACI guidance on the management of anaphylaxis in children (adrenaline IM 10 mcg/kg, max 0.5 mg).'},
  'WAO-ANAPHYLAXIS':    {n:'WAO anaphylaxis', f:'World Allergy Organization Anaphylaxis Guidance (current edition) — adrenaline IM first-line, weight bands, biphasic reaction observation.'},
  'ISCCM-PEDS':         {n:'ISCCM paediatric', f:'Indian Society of Critical Care Medicine paediatric critical care guidance (IVIG, shock, sepsis).'},
  'ATS-EXTUBATION':     {n:'ATS extubation', f:'ATS/CHEST Clinical Practice Guideline on liberation from mechanical ventilation and the prevention of post-extubation stridor (dexamethasone ≥4 h before extubation).'},
  'SCCM-AIRWAY':        {n:'SCCM airway', f:'SCCM guidance on airway management, cuff-leak testing and extubation in the critically ill.'},
  'NICE-CG25':          {n:'NICE croup/seizures', f:'NICE CG25 (fever in under 5s) and NICE croup/seizure guidance.'},
  'NICE-CG169':         {n:'NICE status epilepticus', f:'NICE CG169. Epilepsies: diagnosis and management — emergency treatment of convulsive status epilepticus.'},
  'ISCCM-NEURO':        {n:'ISCCM neurocritical', f:'ISCCM/Indian Neurocritical Care Society guidance on status epilepticus and neurocritical care in India.'},
  'IND-STROKE-GUIDE':   {n:'India stroke guideline', f:'Indian Stroke Society / NVBDCP National Programme for Prevention and Control of Cancer, Diabetes, CVD and Stroke — acute ischaemic stroke management pathway for India.'},
  'IND-HTN':            {n:'India hypertension', f:'Indian Hypertension Society / Hypertension Guidelines for India (IHDI) and the MoHFW India Hypertension Control Initiative.'},
  'ANAPH-IND':          {n:'India anaphylaxis', f:'Indian allergy and immunology consensus on anaphylaxis management and adrenaline availability.'},
  'ACOG-HTN':           {n:'ACOG hypertension', f:'ACOG guidance on hypertensive emergencies in pregnancy.'},
  'ESC-NSTEMI':         {n:'ESC NSTE-ACS', f:'ESC Guidelines for the Management of Acute Coronary Syndromes / Non-ST-Elevation Acute Coronary Syndromes (current edition) — antiplatelet and anticoagulant strategy.'},
  'ISCCM-VTE':          {n:'ISCCM VTE prophylaxis', f:'ISCCM position statement on venous thromboembolism prophylaxis in Indian ICUs; Kakkos SK et al. International clinical practice guidelines on the treatment and prophylaxis of VTE.'},
  'ISCCM-ARDS':         {n:'ISCCM ARDS', f:'ISCCM/Indian consensus on acute respiratory distress syndrome management, lung-protective ventilation and prone positioning in resource-limited ICUs.'},
  'ISCCM-TOX':          {n:'ISCCM toxicology', f:'ISCCM position statement on the intensive care management of acute poisoning and envenomation in India.'},
  'IAP-HAP':            {n:'IAP pneumonia', f:'Indian Academy of Pediatrics. Revised guidelines for the diagnosis and management of pneumonia and hospital-acquired pneumonia in Indian children.'},
  'IAP-NEO':            {n:'IAP neonatology', f:'Indian Academy of Pediatrics. Textbook of Neonatology and IAP clinical practice recommendations for newborn care in India.'},
  'AAP-NEO':            {n:'AAP fetus & newborn', f:'AAP Committee on Fetus and Newborn policy statements — apnoea of prematurity, hypoglycaemia, jaundice, surfactant and neonatal resuscitation.'},
  'AASLD-ASCITES':      {n:'AASLD ascites/SBP', f:'AASLD Guidance on the Management of Ascites, Hepatorenal Syndrome and Spontaneous Bacterial Peritonitis in Cirrhosis (albumin 1.5 g/kg day 1, 1 g/kg day 3).'},
  'BSG-HE':             {n:'BSG liver', f:'British Society of Gastroenterology guidance on hepatic encephalopathy and the management of decompensated cirrhosis.'},
  'ESICM-GLUC':         {n:'ESICM glucose', f:'ESICM/SCCM consensus and clinical review on glycaemic control in the critically ill (target 6–10 mmol/L; avoid hypoglycaemia).'},
  'EXPERT-CONSENSUS-HIET':{n:'HIET consensus', f:'Greene SL et al. Expert Consensus Recommendations: Improving Diagnosis, Management and Outcome From High-Dose Insulin Therapy for Critical Poisoning by Beta-Blockers and Calcium Channel Blockers. J Med Toxicol 2023;19:1–17.'},
  'EXPERT-IRON':        {n:'Iron poisoning', f:'Expert guidance on acute iron overdose — whole-bowel irrigation, deferoxamine 15 mg/kg/h, the vin rose endpoint and the five clinical stages.'},
  'EXTER-HYPO':         {n:'Hypoglycaemia guidance', f:'JBDS-IP. Management of hypoglycaemia in adults in hospital (current edition); Endocrine Society guidance on the evaluation and management of adult hypoglycaemia — octreotide for sulfonylurea-induced hypoglycaemia.'},
  'MHRA-NAC':           {n:'MHRA NAC', f:'MHRA Drug Safety Update and Commission on Human Medicines guidance on intravenous N-acetylcysteine (acetylcysteine) — modified dosing regimens, anaphylactoid reactions and the removal of the risk-factor requirement for treatment.'},
  'NCCN-BRAIN':         {n:'NCCN brain metastases', f:'NCCN Clinical Practice Guidelines in Oncology: Central Nervous System Cancers / Management of Brain Metastases — dexamethasone for symptomatic peritumoral oedema.'},
  'NICE-NG126':         {n:'NICE head injury', f:'NICE NG126 (supersedes CG176). Head injury: assessment and early management.'},
  'NICE-TA':            {n:'NICE technology appraisal', f:'NICE Technology Appraisal guidance — bisphosphonates (zoledronic acid) and bone-modifying agents in malignancy and osteoporosis.'}
};

/* ---------- SYSTEM GROUPS (used for filtering and grouping) ---------- */
if (typeof SYS === 'undefined') { var SYS = {}; }
SYS = {
  resus:        {label:'Resuscitation & Cardiac Arrest', short:'Arrest', desc:'ACLS/APLS arrest drugs, electrolytes for arrest, defibrillation support'},
  arrhythmia:   {label:'Arrhythmia & Rate Control',       short:'Arrhythmia', desc:'Tachy/bradyarrhythmia, rate and rhythm control'},
  vasoactive:   {label:'Vasoactive, Inotrope & Pressor',  short:'Vasoactive', desc:'Titrated infusions and shock support'},
  htn:          {label:'Hypertensive Emergencies',        short:'Hypertension', desc:'IV titratable antihypertensives and BP targets'},
  anticoag:     {label:'Anticoagulation, Lysis & Blood',  short:'Anticoagulation', desc:'Heparin/LMWH, thrombolysis, reversal, blood components'},
  sedation:     {label:'Sedation, Analgesia & Induction', short:'Sedation', desc:'Induction agents, analgesics, antipyretics, reversal'},
  nmba:         {label:'Neuromuscular Blockade & Reversal',short:'NMBA', desc:'Paralytics, reversal agents, malignant hyperthermia'},
  neuro:        {label:'Seizures & Status Epilepticus',   short:'Seizures', desc:'First-, second- and third-line anti-seizure therapy'},
  neurocrit:    {label:'Neurocritical Care',              short:'Neurocritical', desc:'ICP, osmotherapy, stroke, vasospasm, oedema'},
  respiratory:  {label:'Respiratory & Nebulisation',      short:'Respiratory', desc:'Asthma, COPD, croup, bronchiolitis, ARDS, pulmonary HTN'},
  antiinfective:{label:'Antimicrobials & Sepsis',         short:'Antimicrobials', desc:'Empirical and targeted antibacterial, antifungal, antiviral, antiparasitic'},
  endocrine:    {label:'Endocrine & Metabolic',           short:'Endocrine', desc:'DKA/HHS, thyroid, adrenal, glucose, vitamins'},
  electrolyte:  {label:'Electrolytes, Acid–Base & Fluids',short:'Electrolytes', desc:'K⁺, Na⁺, Ca²⁺, Mg²⁺, PO₄, bicarbonate, crystalloids, albumin'},
  renal:        {label:'Renal & Diuretics',               short:'Renal', desc:'Loop/thiazide/K⁺-sparing diuretics, CRRT anticoagulation'},
  tox:          {label:'Toxicology & Antidotes',          short:'Toxicology', desc:'Poisoning, envenomation and specific antidotes'},
  anaphylaxis:  {label:'Anaphylaxis & Allergy',           short:'Anaphylaxis', desc:'First- and second-line anaphylaxis treatment'},
  gi:           {label:'GI, Hepatic & Nutrition',         short:'GI/Hepatic', desc:'Variceal bleed, ulcer bleed, HE, antiemetics, prophylaxis'},
  obs:          {label:'Obstetric Emergencies',           short:'Obstetric', desc:'Eclampsia, PPH, severe hypertension, antenatal steroids'},
  neonatal:     {label:'Neonatal ICU',                    short:'Neonatal', desc:'Neonatal resuscitation, surfactant, apnoea, ductus, sepsis, glucose'},
  misc:         {label:'Programmes & Miscellaneous',      short:'Misc', desc:'Kawasaki, diarrhoea, measles, RHD prophylaxis, others'}
};

/* ---------- PHARMACOLOGICAL CLASS GROUPS (for class-wise filtering) ---------- */
if (typeof CLS === 'undefined') { var CLS = {}; }
CLS = {
  'Adrenergic / sympathomimetic':'Adrenaline · Noradrenaline · Dopamine · Dobutamine · Isoprenaline · Ephedrine · Mephentermine · Phenylephrine · Salbutamol · Terbutaline',
  'Antiarrhythmic':'Amiodarone · Lidocaine · Adenosine · Digoxin · Procainamide · Magnesium',
  'Antihypertensive / rate control':'Esmolol · Metoprolol · Labetalol · Propranolol · Diltiazem · Verapamil · Urapidil · Nicardipine · Nitroglycerin · Nitroprusside · Hydralazine · Clonidine · Nifedipine',
  'Vasodilator / inodilator':'Nitroglycerin · Nitroprusside · Milrinone · Levosimendan · Urapidil · Sildenafil',
  'Sedative–hypnotic / anaesthetic':'Propofol · Midazolam · Etomidate · Ketamine · Thiopentone · Dexmedetomidine · Lorazepam · Diazepam',
  'Opioid analgesic':'Fentanyl · Morphine · Tramadol · Buprenorphine',
  'Non-opioid analgesic / antipyretic':'Paracetamol · Ketorolac · Diclofenac · Nefopam · Ibuprofen',
  'Neuromuscular blocking agent':'Suxamethonium · Rocuronium · Atracurium · Cisatracurium · Vecuronium',
  'Reversal / antagonist':'Sugammadex · Neostigmine · Glycopyrrolate · Flumazenil · Naloxone · Protamine · Vitamin K · Idarucizumab · Phentolamine',
  'Anticonvulsant':'Levetiracetam · Phenytoin · Valproate · Phenobarbitone · Midazolam · Lorazepam · Diazepam · Magnesium',
  'Corticosteroid':'Hydrocortisone · Methylprednisolone · Dexamethasone · Prednisolone · Budesonide',
  'Antimicrobial (antibacterial)':'β-lactams · Carbapenems · Glycopeptides · Aminoglycosides · Polymyxins · Quinolones · Macrolides · Oxazolidinone · Nitroimidazole · Sulfonamide',
  'Antifungal':'Amphotericin B (conventional and liposomal) · Fluconazole · Voriconazole · Caspofungin · Micafungin · Itraconazole',
  'Antiviral':'Aciclovir · Ganciclovir · Oseltamivir · Remdesivir',
  'Antiparasitic / antimycobacterial':'Artesunate · Quinine · Ivermectin · Doxycycline · Cotrimoxazole · HRZE',
  'Anticoagulant / antithrombotic':'Heparin · Enoxaparin · Fondaparinux · Warfarin · Aspirin · Clopidogrel · Ticagrelor · GP IIb/IIIa inhibitors',
  'Fibrinolytic':'Alteplase · Tenecteplase · Streptokinase',
  'Antifibrinolytic / haemostatic':'Tranexamic acid · Vitamin K · Desmopressin · FFP · Cryoprecipitate · Platelets',
  'Electrolyte / mineral':'Potassium chloride · Magnesium sulfate · Calcium gluconate · Calcium chloride · Sodium bicarbonate · Phosphate · Sodium chloride 3%',
  'Diuretic / aquaretic':'Furosemide · Torasemide · Bumetanide · Spironolactone · Acetazolamide · Mannitol · Tolvaptan',
  'Endocrine / metabolic agent':'Insulin · Dextrose · Glucagon · Levothyroxine · PTU · Carbimazole · Octreotide · Desmopressin · Thiamine · Zoledronic acid',
  'Antidote':'N-acetylcysteine · Atropine · Pralidoxime · Methylene blue · Deferoxamine · Hydroxocobalamin · Sodium thiosulfate · Lipid emulsion · Physostigmine · Cyproheptadine · Bromocriptine · Dantrolene · L-carnitine · Pyridoxine · Fomepizole · Ethanol · Digoxin Fab · Idarucizumab · Vitamin K',
  'Immunoglobulin / biological':'IVIG · Anti-snake venom serum · Diphtheria antitoxin · Tetanus immunoglobulin · Alburel/albumin',
  'Bronchodilator / respiratory':'Salbutamol · Ipratropium · Budesonide · Aminophylline · Adrenaline (nebulised) · Hypertonic saline',
  'Uterotonic / obstetric':'Oxytocin · Methylergometrine · Carboprost · Misoprostol · Magnesium sulfate · Labetalol · Hydralazine · Betamethasone',
  'Gastrointestinal agent':'PPI · H2 antagonist · Lactulose · Rifaximin · LOLA · Prokinetic · Antispasmodic · Antiemetic',
  'Vitamin / micronutrient':'Thiamine · Pyridoxine · Vitamin K1 · Vitamin A · Zinc · Folinic acid · L-carnitine'
};
